const COURSES = [
  {
    id: "1",
    name: "Administração",
    icon: "default",
    owner: true,
  },
  {
    id: "2",
    name: "Agronomia",
    icon: "default",
    owner: true,
  },
  {
    id: "3",
    name: "Biomedicina",
    icon: "default",
    owner: true,
  },
  {
    id: "4",
    name: "Ciências Biológicas",
    icon: "default",
    owner: true,
  },
  {
    id: "5",
    name: "Ciências Contábeis",
    icon: "default",
    owner: true,
  },
  {
    id: "6",
    name: "Ciência da Computação",
    icon: "default",
    owner: true,
  },
  {
    id: "7",
    name: "Ciências Econômicas",
    icon: "default",
    owner: true,
  },
  {
    id: "8",
    name: "Comunicação Social",
    icon: "default",
    owner: true,
  },
  {
    id: "9",
    name: "Direito",
    icon: "default",
    owner: true,
  },
  {
    id: "10",
    name: "Enfermagem",
    icon: "default",
    owner: true,
  },
  {
    id: "11",
    name: "Engenharia Civil",
    icon: "default",
    owner: true,
  },
  {
    id: "12",
    name: "Engenharia de Produção",
    icon: "default",
    owner: true,
  },
  {
    id: "13",
    name: "Engenharia Elétrica",
    icon: "default",
    owner: true,
  },
  {
    id: "14",
    name: "Engenharia Mecânica",
    icon: "default",
    owner: true,
  },
  {
    id: "15",
    name: "Engenharia Química",
    icon: "default",
    owner: true,
  },
  {
    id: "16",
    name: "Física",
    icon: "default",
    owner: true,
  },
  {
    id: "17",
    name: "Geografia",
    icon: "default",
    owner: true,
  },
  {
    id: "18",
    name: "Línguas Estrangeiras Aplicadas às Negociações Internacionais      ",
    icon: "default",
    owner: true,
  },
  {
    id: "19",
    name: "Medicina",
    icon: "https://lh3.googleusercontent.com/proxy/Zt8br8RsdsWV528JEFaN8CJeAuuL2X385rqFw7M0b_y59H8PZgsBboTBXOF6UwBPmFGZrtPsxlJ70nxtQE8ZZPMUL0OJ5JCxmdWiCrR3SK0uG6ozxYi3JFbX2vWP36c",
    owner: true,
  },
  {
    id: "20",
    name: "Medicina Veterinária",
    icon: "https://lh3.googleusercontent.com/proxy/Zt8br8RsdsWV528JEFaN8CJeAuuL2X385rqFw7M0b_y59H8PZgsBboTBXOF6UwBPmFGZrtPsxlJ70nxtQE8ZZPMUL0OJ5JCxmdWiCrR3SK0uG6ozxYi3JFbX2vWP36c",
    owner: true,
  },
  {
    id: "21",
    name: "Matemática",
    icon: "https://lh3.googleusercontent.com/proxy/Zt8br8RsdsWV528JEFaN8CJeAuuL2X385rqFw7M0b_y59H8PZgsBboTBXOF6UwBPmFGZrtPsxlJ70nxtQE8ZZPMUL0OJ5JCxmdWiCrR3SK0uG6ozxYi3JFbX2vWP36c",
    owner: true,
  },
  {
    id: "22",
    name: "Química",
    icon: "https://lh3.googleusercontent.com/proxy/Zt8br8RsdsWV528JEFaN8CJeAuuL2X385rqFw7M0b_y59H8PZgsBboTBXOF6UwBPmFGZrtPsxlJ70nxtQE8ZZPMUL0OJ5JCxmdWiCrR3SK0uG6ozxYi3JFbX2vWP36c",
    owner: true,
  },
];

export { COURSES };
